### ISSUE TITLE
About word alignment information

### ISSUE THREAD

**Issue by 6gsn** [yl4579/PL-BERT#9]
Hi, @yl4579 !

Thanks for the exciting work!
I have a question regarding inputs for your model.

In [PnG BERT](https://arxiv.org/abs/2103.15060), the authors used the word position embedding as word alignment information. Also, they found that the information helped to improve the model's performance on MLM, G2P, and P2G tasks.

Predicting grapheme without considering word position could be challenging for the model (of course, you already proved that the model is stable and effective in your paper), but, in my understanding, your model only uses position embedding for phoneme tokens.

So, my question is below;
 - Why has word position embedding not been used for your model?
- Did you have some experiments to find the difference whether using word position embedding?

Thanks!

**Comment by yl4579** [comment]
For the first question, I do not see any reason to use word position embedding in the first place. The reason to use position embeddings in the transformer is that the input has no inherent position information. For example, in the sentence "A dog eats a hot dog," there are two "dogs", but they have different meanings, so you need to specify which dog is which, as the transformer has no inherent representation of the word positions (neither attention nor fully connection layers distinguish these two "dogs"). Since in PnG BERT, the grapheme (word) is an input, word positions are important for the model to deal with cases where some words might occur more than one time. On the other hand, in PL-BERT, the only input is the phoneme, so there is no need to specify the exact position of the word.

I haven't tried to experiment with using word position embedding, and I think the only information it actually provides is the word boundary (i.e., when a word ends in a sequence of phonemes), which is already provided in the input tokens of phonemes, so this information wouldn't be helpful.
